grocery/core/urls.py
from django.urls import path
from .views import (
    home,
    shop,
    registration,
    login,
    contact,
    category_products,
    product_view,
    logout,
    cart,
    add_to_cart,
    remove_from_cart,
    update_cart,
    checkout,
    addaddress,
    alladdresses,
    address_delete,
    allorders,
    payment_success,
    change_pass,
)

app_name='core'
urlpatterns = [
    path('', home, name='Home'),
    path('shop/', shop, name='Shop'),
    path('registration/', registration, name="Registration"),
    path('login/', login, name="Login"),
    path('logout/', logout, name="Logout"),
    path('contact', contact, name="Contact"),

    # Products Pages
    path('category/<slug>/', category_products, name="Category_Product"),
    path('product/<slug>/', product_view, name="Product"),

    # Cart Page 
    path('cart/', cart, name='Cart'),
    path('add-to-cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<int:cart_item_id>/', remove_from_cart, name='remove_from_cart'),
    path('update-cart/', update_cart, name='update_cart'),
    
    # Check out pages
    path('checkout/', checkout, name="Checkout"),
    path('payment/success/<payment_id>/', payment_success, name='payment_success'),

    # account section...
    path('add/address/', addaddress, name="Add_address"),
    path('all/address/', alladdresses, name="All_address"),
    path('address/delete/<id>/', address_delete, name="Address_delete"),
    path('all/orders/', allorders, name="All_orders"),
    path('change/password', change_pass, name="change-pass"),
]

# slug, str, int is accepted as a django url parameter.

grocery/grocery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),

    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

grocery/core/models.py
from django.db import models
from django.contrib.auth.models import User
from product.models import (
    Product,
)

# Create your models here.

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE) # user --> Address (one to many relationship)
    phone1 = models.CharField(max_length=15)
    phone2 = models.CharField(max_length=15)
    address = models.TextField()
    country = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    postal = models.CharField(max_length=10)
    address_type = models.CharField(max_length=100)

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def cart_item_count(self):
        return CartItem.objects.filter(cart__user = self.user).count()

    def cart_total(self):
        cart = Cart.objects.get(user = self.user)
        cart_items = cart.cartitem_set.all()
        return sum(item.product.product_price * item.quantity for item in cart_items)

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

class Order(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    products = models.ManyToManyField(Product, through = 'OrderedProduct')
    order_address = models.ForeignKey(Address, verbose_name="Order Address", on_delete=models.SET_NULL, null=True)
    order_amount = models.FloatField(default=0, verbose_name='Order Amount')
    payment_status = models.CharField(max_length = 20, choices = [('pending', 'Pending'), ('paid', 'Paid')])
    razorpay_order_id = models.CharField( max_length=250, null=True, blank=True)
    razorpay_payment_id = models.CharField( max_length=250, null=True, blank=True)
    razorpay_payment_signeture = models.CharField( max_length=250, null=True, blank=True)

    # def __str__(self):
    #     return self.user

class OrderedProduct(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    order_date = models.DateField(auto_now=True)

# Order (1 or many product) as it is OrderedProduct(1 or many orders)  ---> many to many relationship

grocery/product/models.py
from django.db import models
from django.utils.text import slugify
import string
import random

# Create your models here.

# raihan mistry gafv fhjwg  ---> raihan-mistry-gafv-hdfndzs
# Creation of Category Model
class Category(models.Model):
    category_name = models.CharField(max_length=100, verbose_name='Category Name', unique=True)
    category_slug = models.SlugField(max_length=100, blank=True, verbose_name='Category Slug')
    category_image = models.ImageField(upload_to='Category_Images', verbose_name='Category Image', null=True, blank=True)
    category_desc = models.TextField(verbose_name='Category Description')
    category_created_at = models.DateField(auto_now=True)



    def save(self, *args, **kwargs):
        self.category_slug = slugify(self.category_name)
        super(Category,self).save(*args, **kwargs)

    def __str__(self):
        return self.category_name
    

# Product Quantity
class Quantity(models.Model):
    quantity_name = models.CharField(max_length=100, unique=True)
    quantity_desc = models.CharField(max_length=250, blank=True)
    quantity_created_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.quantity_name
    
# Product Size
class Size(models.Model):
    size_name = models.CharField(max_length=100, unique=True)
    size_name_desc = models.CharField(max_length=250, blank=True)
    size_created_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.size_name

# Creation of Product Model
class Product(models.Model):
    category = models.ForeignKey(Category, verbose_name="Category", on_delete=models.CASCADE)
    product_name = models.CharField(max_length=100, unique=True)
    product_short_desc = models.CharField(max_length=250)
    product_long_desc = models.TextField()
    product_image = models.ImageField(upload_to='Product_images', null=True, blank=True)
    product_price = models.FloatField(default=0)
    product_created_at = models.DateField(auto_now=True)
    Quantity = models.ForeignKey(Quantity, verbose_name=("Quantities"), on_delete=models.RESTRICT)
    Size = models.ForeignKey(Size, verbose_name='Product Size', on_delete=models.CASCADE)
    product_id = models.CharField(max_length=100, blank=True, verbose_name='Product id auto generated')
    product_sell_count = models.BigIntegerField(default=0)

    def save(self, *args, **kwargs):
        randomid = ''.join([random.choice(string.ascii_letters + string.digits) for n in range(10)])
        self.product_id = str(self.product_name+'_'+randomid)
        super(Product,self).save(*args, **kwargs)

    def __str__(self):
        return self.product_name

# cascade, protect, restrict, set_null, set

grocery/core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib import messages
from product.models import (
    Category,
    Product,
)
from .models import (
    Cart,
    CartItem,
    Address,
    Order,
    OrderedProduct,
)
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
import razorpay
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.hashers import check_password
# Create your views here.

def home(request):
    categories_obj = Category.objects.all()
    latest_products = Product.objects.all().order_by('-id')[:6]
    top_buying_products = Product.objects.all().order_by('-product_sell_count')[:6]
    top_rated_product = Product.objects.all().order_by('?')[:6]
    featured_product = Product.objects.all().order_by('?')[:12]
    context = {
        'categories': categories_obj,
        'latest_products': latest_products,
        'top_buying_products':top_buying_products,
        'top_rated_product': top_rated_product,
        'featured_product':featured_product,
    }
    return render(request, 'grocery/index.html', context)

def shop(request):
    product_count = Product.objects.all().order_by('?').count()
    categories_obj = Category.objects.all()
    products_obj = Product.objects.all().order_by('?')
    paginator = Paginator(products_obj, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'categories': categories_obj,
        'products': page_obj,
        'product_count':product_count,
    }
    return render(request, 'grocery/shop.html', context)

def registration(request):
    if request.method == "POST":
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        email = request.POST.get('email')
        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')

        if User.objects.filter(username = username):
            messages.error(request, 'username field already exist. try with a different one.')
            return redirect('core:Registration')
        
        if User.objects.filter(email = email):
            messages.error(request, 'email field already exist. try with a different one.')
            return redirect('core:Registration')
        
        if password1 != password2:
            messages.error(request, 'password and confirm password field are not match.')
            return redirect('core:Registration')
        
        user_obj = User(first_name = first_name, last_name = last_name, username = username, email = email)
        user_obj.set_password(password1)
        user_obj.save()

        messages.success(request, 'Registration successfully done. go to login page for login.')
        return redirect('core:Login')
    
    return render(request, 'grocery/registration.html')

def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        username_check = User.objects.filter(username = username)
        if not username_check:
            messages.error(request, 'username field does not exist. try with the correct one.')
            return redirect('core:Login')
        
        user = authenticate(request, username = username, password = password)
        if not user:
            messages.error(request, 'Invalid login credentials')
            return redirect('core:Login')
        else:
            auth_login(request, user)
            messages.success(request, f'login done , welcome {username} to your Grocery partner')
            return redirect('core:Home')
            
    return render(request, 'grocery/login.html')

def logout(request):
    auth_logout(request)
    messages.success(request, 'Thanks for spending some quality times with us.')
    return redirect('core:Home')

def contact(request):
    return render(request, 'grocery/contact.html')

def category_products(request, slug):
    categories_obj = Category.objects.all()
    cat_obj = Category.objects.get(category_slug = slug)
    id = cat_obj.id
    product_obj = Product.objects.all().filter(category = id)
    paginator = Paginator(product_obj, 12)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    all_products = Product.objects.all()
    context = {
        'category':cat_obj,
        'categories': categories_obj,
        'products': page_obj,
        'all_products':all_products,
    }
    return render(request, 'grocery/categoryview.html', context)

def product_view(request, slug):
    product_obj = Product.objects.get(product_id = slug)
    relat_id = product_obj.category
    cat_obj = Category.objects.get(category_name = relat_id)
    id = cat_obj.id
    relate_item = Product.objects.all().filter(category = id)[:4]
    categories = Category.objects.all()
    context = {
        'relate_item':relate_item,
        'product':product_obj,
        'categories':categories,
    }
    return render(request, 'grocery/productview.html', context)

# cart section 

login_required(login_url='core:Login')
def cart(request):
    cart = Cart.objects.get(user=request.user)
    cart_items = cart.cartitem_set.all()
    cart_total = sum(item.product.product_price * item.quantity for item in cart_items)
    context = {
        'cart':cart,
        'cart_items': cart_items,
        'cart_total':cart_total,
        }
    return render(request, 'grocery/cart.html', context)

@login_required(login_url='core:Login')
def add_to_cart(request, product_id):
    product = Product.objects.get(pk=product_id)
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart_item, item_created = CartItem.objects.get_or_create(cart=cart, product=product)
    if not item_created:
        cart_item.quantity += 1
        cart_item.save()
    return redirect('core:Cart')

@login_required(login_url='core:Login')
def update_cart(request):
    if request.method == 'POST':
        cart_item_ids = request.POST.getlist('cart_item')
        quantities = request.POST.getlist('quantity')
        for cart_item_id, quantity in zip(cart_item_ids, quantities):
            cart_item = CartItem.objects.get(pk=cart_item_id)
            cart_item.quantity = quantity
            cart_item.save()
        return redirect('core:Cart')

@login_required(login_url='core:Login')
def remove_from_cart(request, cart_item_id):
    cart_item = CartItem.objects.get(pk=cart_item_id)
    cart_item.delete()
    return redirect('core:Cart')

# Checkout section....


@login_required(login_url='core:Login')
def checkout(request):
    cart = Cart.objects.get(user=request.user)
    cart_items = cart.cartitem_set.all()
    cart_total = sum(item.product.product_price * item.quantity for item in cart_items)
    address_obj = Address.objects.filter(user = request.user).all()
    client = razorpay.Client(auth=(settings.RAZOR_KEY_ID, settings.RAZOR_KEY_SECRET))

    payment = client.order.create({
        'amount': cart_total * 100,
        'currency': 'INR',
        'payment_capture': 1,  # Auto-capture payments
    })
    order = Order(user = request.user, razorpay_order_id = payment['id'])
    order.save()

    context = {
        'cart_items':cart_items,
        'cart_total':cart_total,
        'address': address_obj,
        'payment': payment,

    }
    return render(request, 'grocery/checkout.html', context)


def payment_success(request, payment_id):
    print(payment_id)
    cart = Cart.objects.get(user=request.user)
    cart_items = cart.cartitem_set.all()
    cart_total = sum(item.product.product_price * item.quantity for item in cart_items)
    order = Order.objects.get(razorpay_order_id = payment_id)

    order.order_amount = cart_total
    order.payment_status = 'paid'
    order.save()
    for cart_item in cart_items:
        orderedProduct_obj = OrderedProduct.objects.create(
            user = request.user,
            order = order,
            product = cart_item.product,
            quantity = cart_item.quantity,
        )
        product_obj = Product.objects.get(id = cart_item.product.id)
        product_obj.product_sell_count += orderedProduct_obj.quantity
    cart_items.delete()
    context = {
        'order':order,
    }
    return render(request, 'grocery/payment-success.html', context)


# Accounts Section ......

@login_required(login_url='core:Login')
def addaddress(request):
    if request.method == "POST":
        user = request.user
        phone1 = request.POST.get('phone1')
        phone2 = request.POST.get('phone2')
        address = request.POST.get('address')
        country = request.POST.get('country')
        state = request.POST.get('state')
        city = request.POST.get('city')
        postal = request.POST.get('postal')
        address_type = request.POST.get('address_type')

        address_obj = Address(user = user, phone1 = phone1, phone2 = phone2, address = address, country = country, state = state, city = city, postal = postal, address_type = address_type)
        address_obj.save()
        messages.success(request, 'New Address added Successfully')
        return redirect('core:Add_address')

    return render(request, 'grocery/addaddress.html')

@login_required(login_url='core:Login')
def alladdresses(request):
    user = request.user
    address_obj = Address.objects.all().filter(user = user)

    context = {
        'address':address_obj,
    }
    return render(request, 'grocery/alladdresses.html', context)

@login_required(login_url='core:Login')
def address_delete(request, id):
    address_obj = Address.objects.get(id = id)
    address_obj.delete()

    messages.success(request, 'Address deleted Successfully')

grocery/product/views.py
from django.shortcuts import render

# Create your views here.

grocery/core/templates/grocery/cart.html
{% extends 'grocery/base.html' %}
{% load static %}

{% block title %}
    Cart
{% endblock title %}
    

{% block content %}
    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'grocery/img/breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>Shopping Cart</h2>
                        <div class="breadcrumb__option">
                            <a href="./index.html">Home</a>
                            <span>Shopping Cart</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Shoping Cart Section Begin -->
    <section class="shoping-cart spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <form action="{% url 'core:update_cart' %}" method="post">
                    {% csrf_token %}
                        <div class="shoping__cart__table">
                            <table>
                                <thead>
                                    <tr>
                                        <th class="shoping__product">Products</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                        <th>Total</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                    {% if cart_items %}
                                    
                                    {% for item in cart_items %}
                                        <tr>
                                            <td class="shoping__cart__item">
                                                <img src="{{item.product.product_image.url}}" width="200" alt="">
                                                <h5>{{item.product.product_name}}</h5>
                                            </td>
                                            <td class="shoping__cart__price">
                                                ₹ {{item.product.product_price}} /{{item.product.Quantity}}
                                            </td>
                                            <td class="shoping__cart__quantity">
                                                <div class="quantity">
                                                    <input type="hidden" name="cart_item" value="{{ item.id }}">
                                                    <div class="pro-qty">
                                                        <input type="text" name="quantity" value="{{item.quantity}}">
                                                    </div>
                                                </div>
                                            </td>
                                            <td class="shoping__cart__total">
                                                ₹ {% widthratio item.product.product_price 1 item.quantity %}
                                            </td>
                                            <td class="shoping__cart__item__close">
                                                <a href="{% url 'core:remove_from_cart' item.id %}" class="text-dark"><i class="fa-solid fa-xmark"></i></a>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                        
                                        
                                    {% endif %}
                                        
                                </tbody>
                            </table>
                        </div>
                        <div class="col-lg-12">
                            <div class="shoping__cart__btns">
                                <a href="{% url 'core:Shop' %}" class="primary-btn cart-btn">CONTINUE SHOPPING</a>
                                <button type="submit" class="primary-btn cart-btn cart-btn-right"><span class="icon_loading"></span>
                                    Upadate Cart</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6">
                    
                </div>
                <div class="col-lg-6">
                    <div class="shoping__checkout">
                        <h5>Cart Total</h5>
                        <ul>
                            <li>Subtotal <span>₹ {{cart_total}}</span></li>
                            <li>Total <span>₹ {{cart_total}}</span></li>
                        </ul>
                        
                        {% if cart_total != 0 %}
                            <a href="{% url 'core:Checkout' %}" class="primary-btn">PROCEED TO CHECKOUT</a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Shoping Cart Section End -->

    {% endblock content %}

grocery/core/templates/grocery/productview.html
{% extends 'grocery/base.html' %}
{% load static %}
{% block title %}
    Product
{% endblock title %}

{% block content %}
 
    <!-- Hero Section Begin -->
    <section class="hero hero-normal">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="hero__categories">
                        <div class="hero__categories__all">
                            <i class="fa fa-bars"></i>
                            <span>All categories</span>
                        </div>
                        <ul>   
                            {% if categories %}
                                {% for category in categories %}
                                    <li><a href="{% url 'core:Category_Product' category.category_slug %}">{{category.category_name}}</a></li>
                                {% endfor %} 
                            {% else %}
                                <li><p class="text-danger">No Categories Found</p></li> 
                            {% endif %}  
                        </ul>
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="hero__search">
                        <div class="hero__search__form">
                            <form action="#">
                                <div class="hero__search__categories">
                                    All Categories
                                    <span class="arrow_carrot-down"></span>
                                </div>
                                <input type="text" placeholder="What do yo u need?">
                                <button type="submit" class="site-btn">SEARCH</button>
                            </form>
                        </div>
                        <div class="hero__search__phone">
                            <div class="hero__search__phone__icon">
                                <i class="fa fa-phone"></i>
                            </div>
                            <div class="hero__search__phone__text">
                                <h5>+65 11.188.888</h5>
                                <span>support 24/7 time</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Hero Section End -->

    <!-- Breadcrumb Section Begin -->
    <section class="breadcrumb-section set-bg" data-setbg="{% static 'grocery/img/breadcrumb.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <div class="breadcrumb__text">
                        <h2>{{product.category}}</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Breadcrumb Section End -->

    <!-- Product Details Section Begin -->
    <section class="product-details spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6">
                    <div class="product__details__pic">
                        <div class="product__details__pic__item">
                            <img class="product__details__pic__item--large"
                                src="{{product.product_image.url}}" alt="">
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="product__details__text">
                        <h3>{{product.product_name}}</h3>
                        <span>{{product.product_short_desc}}</span>
                        <div class="product__details__rating">
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star"></i>
                            <i class="fa fa-star-half-o"></i>
                            <span>(18 reviews)</span>
                        </div>
                        <div class="product__details__price">₹ {{product.product_price}}</div>
                        <p>{{product.product_long_desc}}</p>
                        <a href="{% url 'core:add_to_cart' product.id %}" class="primary-btn">ADD TO CARD</a>
                        <a href="#" class="heart-icon"><span class="icon_heart_alt"></span></a>
                        <ul>
                            <li><b>Availability</b> <span>In Stock</span></li>
                            <li><b>Shipping</b> <span>01 day shipping. <samp>Free pickup today</samp></span></li>
                            <li><b>Quantity</b> <span>1 {{product.Quantity}}</span></li>
                            <li><b>Unit sell</b> <span>{{product.product_sell_count}}</span></li>
                            <li><b>Share on</b>
                                <div class="share">
                                    <a href="#"><i class="fa-brands fa-facebook"></i></a>
                                    <a href="#"><i class="fa-brands fa-twitter"></i></a>
                                    <a href="#"><i class="fa-brands fa-linkedin"></i></a>
                                    <a href="#"><i class="fa-brands fa-pinterest"></i></a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Product Details Section End -->

    <!-- Related Product Section Begin -->
    <section class="related-product">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-title related__product__title">
                        <h2>Related Product</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                
                {% if relate_item %}
                    
                    {% for item in relate_item %}
                        <div class="col-lg-3 col-md-4 col-sm-6">
                            <div class="product__item">
                                <div class="product__item__pic set-bg" data-setbg="{{item.product_image.url}}">
                                    <ul class="product__item__pic__hover">
                                        <li><a href="#"><i class="fa fa-heart"></i></a></li>
                                        <li><a href="{% url 'core:add_to_cart' product.id %}"><i class="fa fa-shopping-cart"></i></a></li>
                                    </ul>
                                </div>
                                <div class="product__item__text">
                                    <h6><a href="{% url 'core:Product' item.product_id %}">{{item.product_name}}</a></h6>
                                    <h5>₹ {{item.product_price}} /{{item.Quantity}}</h5>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                        
                {% endif %}
                    
            </div>
        </div>
    </section>
    <!-- Related Product Section End -->
{% endblock content %}